yelp_clone/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'restaurants' => 'restaurants#index'
  resources :restaurants, shallow: true do
    resources :reviews do
      resources :endorsements
    end
  end

  root to: "restaurants#index"

end

yelp_clone/app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
  belongs_to :review
end

yelp_clone/app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "https://s3-us-west-2.amazonaws.com/yelp-clone-makers/restaurants/images/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  belongs_to :user
  has_many :reviews, dependent: :destroy
  validates :name, length: {minimum: 3}, uniqueness: true

  def average_rating
    return 'N/A' if reviews.none?
    reviews.average(:rating)
  end

end

yelp_clone/app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant
  validates :rating, inclusion: (1..5)
  has_many :endorsements
end

yelp_clone/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
  has_many :restaurants
  has_many :reviews
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      # user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
    end
  end

end

yelp_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

yelp_clone/app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController

  def create
    @review = Review.find(params[:review_id])
    @review.endorsements.create
    render json: {new_endorsement_count: @review.endorsements.count}
  end
end

yelp_clone/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user = current_user
    if @restaurant.save
      redirect_to restaurants_path
    else
      render 'new'
    end
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :image)
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
    unless @restaurant.user == current_user
      flash[:notice] = 'Can only edit restaurants you have created'
      redirect_to '/restaurants'
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to '/restaurants'
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.user == current_user
      @restaurant.destroy
      flash[:notice] = 'Restaurant deleted successfully'
    else
      flash[:notice] = 'Can only delete restaurants you have created'
    end
    redirect_to '/restaurants'
  end
end

yelp_clone/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @restaurant.reviews.create(review_params)
    redirect_to restaurants_path
  end

  def review_params
    params.require(:review).permit(:thoughts, :rating)
  end

end

yelp_clone/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end



end

yelp_clone/app/helpers/application_helper.rb
module ApplicationHelper
end

yelp_clone/app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

yelp_clone/app/helpers/restaurants_helper.rb
module RestaurantsHelper

end

yelp_clone/app/helpers/reviews_helper.rb
module ReviewsHelper
  def star_rating(rating)
    return rating unless rating.respond_to?(:round)
    remainder = (5-rating)
    '★' * rating.round + "☆" * remainder
  end
end

yelp_clone/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta (charset="UTF-8")
    %title YelpClone
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    = notice
    = alert
    = yield

    - if user_signed_in?
      = link_to "Sign out", destroy_user_session_path, method: :delete
    - else
      = link_to "Sign in", new_user_session_path
      = link_to "Sign up", new_user_registration_path

yelp_clone/app/views/restaurants/_form.html.haml
= form_for @restaurant, html: {multipart: true} do |f|
  = f.file_field :image
  = f.label :name
  = f.text_field :name
  = f.submit

yelp_clone/app/views/restaurants/edit.html.haml
= render 'form'

yelp_clone/app/views/restaurants/index.html.haml
- if @restaurants.any?
  - @restaurants.each do |restaurant|
    %h3
      Review for
      = restaurant.name
      = image_tag restaurant.image.url(:thumb)

    - if restaurant.reviews.any?
      %ul
        - restaurant.reviews.each do |review|
          %li
            #{review.thoughts} Average rating: #{star_rating(restaurant.average_rating)}
            = link_to "Endorse", review_endorsements_path(review), class: 'endorsements-link'
            %span.endorsements_count= review.endorsements.count
            = 'endorsement'.pluralize review.endorsements.count

    - else
      %p No reviews
    %h2= link_to restaurant.name, restaurant_path(restaurant)
    %h3
      Average rating:
      = star_rating(restaurant.average_rating)
    = link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant)
    = link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete
    = link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant)
- else
  No restaurants yet

%a(href='/restaurants/new') Add a restaurant

yelp_clone/app/views/restaurants/new.html.haml
- if @restaurant.errors.any?
  %section#errors
    %h2
      = pluralize @restaurant.errors.count, "error"
      prohibited this restaurant from being saved:
    %ul
      - @restaurant.errors.full_messages.each do |message|
        %li= message
= render 'form'

yelp_clone/app/views/restaurants/show.html.haml
%p= @restaurant.name
%p= @restaurant.description
%ul
- @restaurant.reviews.each do |review|
  %li
    = review.thoughts
    %strong = review.rating
    /5

yelp_clone/app/views/reviews/new.html.haml
= form_for [@restaurant, @review] do |f|
  = f.label :thoughts
  = f.text_area :thoughts
  = f.label :rating
  = f.select :rating, (1..5)
  = f.submit 'Leave Review'